### PR TITLE
Cluster restart option

### PR DESCRIPTION
**Pull request by mkang32**
Pull Request Checklist
 - [ ] Pull request is based on WIP branch
 - [ ] Pull request includes a description of the change and the reason behind it
 - [ ] `pytest` passes locally
 - [ ] `flake8 apparate tests` passes locally
 - [ ] CHANGELOG has been updated
 - [ ] Version in `_version.py` has been updated
 - [ ] README and docs have been updated (if applicable)

(i didn't do any of above)

---
This change is [Reviewable](https://reviewable.io/reviews/aquicore/apparate/1)

### CODE REVIEW

**Review by mgsosna — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aquicore/apparate/1)* status: all files reviewed, 3 unresolved discussions (waiting on @mkang32, @msakauye, and @nate-aq)

___
*[apparate/cli.py, line 11 at r1](https://reviewable.io/reviews/aquicore/apparate/1#-LkPdPFU9JLZGjF55elz:-LkPdPFU9JLZGjF55em-:bywrwmr) ([raw file](https://github.com/aquicore/apparate/blob/0bf9952508b19a087239b5c4d962f29ad28f6c95/apparate/cli.py#L11)):*
> ```Python
>     if not value or ctx.resilient_parsing:
>         return
>     click.echo('This is a test. Version {}'.format(__version__))
> ```

Maybe change to "This is Aquicore version..."
___
*[apparate/cli_commands.py, line 141 at r1](https://reviewable.io/reviews/aquicore/apparate/1#-LkPdX3uAZdA9QoHoX0I:-LkPdX3v39vnBAdP_R2I:b-wthvhi) ([raw file](https://github.com/aquicore/apparate/blob/0bf9952508b19a087239b5c4d962f29ad28f6c95/apparate/cli_commands.py#L141)):*
> ```Python
> 
> 
> @click.command(short_help='upload an egg and update clusters')
> ```

Why @click?
___
*[apparate/update_databricks_library.py, line 505 at r1](https://reviewable.io/reviews/aquicore/apparate/1#-LkPdrdh1j9DXLckKVqY:-LkPdrdh1j9DXLckKVqZ:b-pweyhx) ([raw file](https://github.com/aquicore/apparate/blob/0bf9952508b19a087239b5c4d962f29ad28f6c95/apparate/update_databricks_library.py#L505)):*
> ```Python
> 
>     # all-cluster-statuses endpoint only returns running clusters
>     # TODO: get all the list of clusters including pending and terminated,
> ```

Is there a plan to address this?

**Review by msakauye — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aquicore/apparate/1)* status: all files reviewed, 3 unresolved discussions (waiting on @click, @mgsosna, @mkang32, and @nate-aq)

___
*[apparate/cli.py, line 11 at r1](https://reviewable.io/reviews/aquicore/apparate/1#-LkPdPFU9JLZGjF55elz:-LkPhPPk4-Ti3Gb47nJy:b-td2h6d) ([raw file](https://github.com/aquicore/apparate/blob/0bf9952508b19a087239b5c4d962f29ad28f6c95/apparate/cli.py#L11)):*
<details><summary><i>Previously, mgsosna (Matt (Grobis) Sosna) wrote…</i></summary><blockquote>

Maybe change to "This is Aquicore version..."
</blockquote></details>

I'd just delete it
___
*[apparate/cli_commands.py, line 141 at r1](https://reviewable.io/reviews/aquicore/apparate/1#-LkPdX3uAZdA9QoHoX0I:-LkPg_SV1FhvX8UBcHv-:b-8h877p) ([raw file](https://github.com/aquicore/apparate/blob/0bf9952508b19a087239b5c4d962f29ad28f6c95/apparate/cli_commands.py#L141)):*
<details><summary><i>Previously, mgsosna (Matt (Grobis) Sosna) wrote…</i></summary><blockquote>

Why @click?
</blockquote></details>

I had the same question, in this case click is "Command Line Interface Creation Kit" (https://click.palletsprojects.com/en/7.x/), so these are just creating a new CLI command with the given params

**Review by mkang32 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aquicore/apparate/1)* status: all files reviewed, 3 unresolved discussions (waiting on @click, @mgsosna, and @nate-aq)

___
*[apparate/cli.py, line 11 at r1](https://reviewable.io/reviews/aquicore/apparate/1#-LkPdPFU9JLZGjF55elz:-LkQIvM-2FV3M_U28fVm:b-896fix) ([raw file](https://github.com/aquicore/apparate/blob/0bf9952508b19a087239b5c4d962f29ad28f6c95/apparate/cli.py#L11)):*
<details><summary><i>Previously, msakauye (Mark) wrote…</i></summary><blockquote>

I'd just delete it
</blockquote></details>

Done.
___
*[apparate/cli_commands.py, line 141 at r1](https://reviewable.io/reviews/aquicore/apparate/1#-LkPdX3uAZdA9QoHoX0I:-LkQIwpV5Lqoe6O3v8cB:bmime8e) ([raw file](https://github.com/aquicore/apparate/blob/0bf9952508b19a087239b5c4d962f29ad28f6c95/apparate/cli_commands.py#L141)):*
<details><summary><i>Previously, msakauye (Mark) wrote…</i></summary><blockquote>

I had the same question, in this case click is "Command Line Interface Creation Kit" (https://click.palletsprojects.com/en/7.x/), so these are just creating a new CLI command with the given params
</blockquote></details>

Correct. It is a tool to create a CLI command. 
___
*[apparate/update_databricks_library.py, line 505 at r1](https://reviewable.io/reviews/aquicore/apparate/1#-LkPdrdh1j9DXLckKVqY:-LkQJ4dG9yFEaXksDilu:b-v3wz7n) ([raw file](https://github.com/aquicore/apparate/blob/0bf9952508b19a087239b5c4d962f29ad28f6c95/apparate/update_databricks_library.py#L505)):*
<details><summary><i>Previously, mgsosna (Matt (Grobis) Sosna) wrote…</i></summary><blockquote>

Is there a plan to address this?
</blockquote></details>

Not yet. If we find this really important in our use, we can come back to this.

**Review by mgsosna — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/aquicore/apparate/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nate-aq)

**Review by nate-aq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/aquicore/apparate/1)* status: all files reviewed, 7 unresolved discussions (waiting on @mkang32)

___
*[apparate/cli_commands.py, line 84 at r2](https://reviewable.io/reviews/aquicore/apparate/1#-LkQVv9k7-VIHDEwkFmj:-LkQVv9k7-VIHDEwkFmk:b-ejgpt0) ([raw file](https://github.com/aquicore/apparate/blob/d7d27dd1426cf7e491d7ce385189fc11ff2d9d6f/apparate/cli_commands.py#L84)):*
> ```
> update_clusters=False,
> ```
Please remove the trailing comma.
___
*[apparate/cli_commands.py, line 137 at r2](https://reviewable.io/reviews/aquicore/apparate/1#-LkQW4Qx4JPatAc88yt1:-LkQW4Qx4JPatAc88yt2:b-ejgpt0) ([raw file](https://github.com/aquicore/apparate/blob/d7d27dd1426cf7e491d7ce385189fc11ff2d9d6f/apparate/cli_commands.py#L137)):*
> ```
> update_clusters=False,
> ```
Please remove the trailing comma.
___
*[apparate/cli_commands.py, line 147 at r2](https://reviewable.io/reviews/aquicore/apparate/1#-LkQWKEU4lbbpTTOoCEf:-LkQWKEU4lbbpTTOoCEg:b-30gezf) ([raw file](https://github.com/aquicore/apparate/blob/d7d27dd1426cf7e491d7ce385189fc11ff2d9d6f/apparate/cli_commands.py#L147)):*
> ```
> required=True,
> ```
Please remove the trailing comma.
___
*[apparate/cli_commands.py, line 153 at r2](https://reviewable.io/reviews/aquicore/apparate/1#-LkQW_KeBHxUqCLWVL3b:-LkQW_KeBHxUqCLWVL3c:bf2qqo0) ([raw file](https://github.com/aquicore/apparate/blob/d7d27dd1426cf7e491d7ce385189fc11ff2d9d6f/apparate/cli_commands.py#L153)):*
> ```
> ' - optional, read from `.apparatecfg` if not provided'),
> ```
Please remove the trailing comma.
___
*[apparate/cli_commands.py, line 161 at r2](https://reviewable.io/reviews/aquicore/apparate/1#-LkQWZAF-pMnjZZ2_gZw:-LkQWZAGCL-NGTX2wAW0:bui0quw) ([raw file](https://github.com/aquicore/apparate/blob/d7d27dd1426cf7e491d7ce385189fc11ff2d9d6f/apparate/cli_commands.py#L161)):*
> ```
> '- optional, read from `.apparatecfg` if not provided'),
> ```
Please remove the trailing comma.
___
*[apparate/cli_commands.py, line 168 at r2](https://reviewable.io/reviews/aquicore/apparate/1#-LkQWY0NCkXPgohmfwH0:-LkQWY0NCkXPgohmfwH1:b-hz38qj) ([raw file](https://github.com/aquicore/apparate/blob/d7d27dd1426cf7e491d7ce385189fc11ff2d9d6f/apparate/cli_commands.py#L168)):*
> ```
> show_default=True,
> ```
Please remove the trailing comma.
___
*[apparate/cli_commands.py, line 195 at r2](https://reviewable.io/reviews/aquicore/apparate/1#-LkQWVQk1ksRdtJ8YOqX:-LkQWVQk1ksRdtJ8YOqY:b-prkogh) ([raw file](https://github.com/aquicore/apparate/blob/d7d27dd1426cf7e491d7ce385189fc11ff2d9d6f/apparate/cli_commands.py#L195)):*
> ```
> update_clusters=True,
> ```
Please remove the trailing comma.

**Review by nate-aq — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aquicore/apparate/1)* status: all files reviewed, 7 unresolved discussions (waiting on @mkang32)

**Review by nate-aq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aquicore/apparate/1)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @mgsosna, @mkang32, @msakauye, and @nate-aq)

___
*[apparate/cli_commands.py, line 84 at r2](https://reviewable.io/reviews/aquicore/apparate/1#-LkQVv9k7-VIHDEwkFmj:-LkUgREb3UN3b2yEEG7T:b2nhktp) ([raw file](https://github.com/aquicore/apparate/blob/d7d27dd1426cf7e491d7ce385189fc11ff2d9d6f/apparate/cli_commands.py#L84)):*
<details><summary><i>Previously, nate-aq (Nathan Bittinger) wrote…</i></summary><blockquote>

> ```
> update_clusters=False,
> ```
Please remove the trailing comma.
</blockquote></details>

OK.
___
*[apparate/cli_commands.py, line 137 at r2](https://reviewable.io/reviews/aquicore/apparate/1#-LkQW4Qx4JPatAc88yt1:-LkUgTlsErRXUptPGuaD:b2nhktp) ([raw file](https://github.com/aquicore/apparate/blob/d7d27dd1426cf7e491d7ce385189fc11ff2d9d6f/apparate/cli_commands.py#L137)):*
<details><summary><i>Previously, nate-aq (Nathan Bittinger) wrote…</i></summary><blockquote>

> ```
> update_clusters=False,
> ```
Please remove the trailing comma.
</blockquote></details>

OK.
___
*[apparate/cli_commands.py, line 147 at r2](https://reviewable.io/reviews/aquicore/apparate/1#-LkQWKEU4lbbpTTOoCEf:-LkUgV259JVhxg_UCbl2:b-xufi0d) ([raw file](https://github.com/aquicore/apparate/blob/d7d27dd1426cf7e491d7ce385189fc11ff2d9d6f/apparate/cli_commands.py#L147)):*
> OK.
OK.
___
*[apparate/cli_commands.py, line 153 at r2](https://reviewable.io/reviews/aquicore/apparate/1#-LkQW_KeBHxUqCLWVL3b:-LkUgVjr96QfV_oTbXZ3:b2nhktp) ([raw file](https://github.com/aquicore/apparate/blob/d7d27dd1426cf7e491d7ce385189fc11ff2d9d6f/apparate/cli_commands.py#L153)):*
<details><summary><i>Previously, nate-aq (Nathan Bittinger) wrote…</i></summary><blockquote>

> ```
> ' - optional, read from `.apparatecfg` if not provided'),
> ```
Please remove the trailing comma.
</blockquote></details>

OK.
___
*[apparate/cli_commands.py, line 161 at r2](https://reviewable.io/reviews/aquicore/apparate/1#-LkQWZAF-pMnjZZ2_gZw:-LkUgWSf6HPPzGj9wf2B:b2nhktp) ([raw file](https://github.com/aquicore/apparate/blob/d7d27dd1426cf7e491d7ce385189fc11ff2d9d6f/apparate/cli_commands.py#L161)):*
<details><summary><i>Previously, nate-aq (Nathan Bittinger) wrote…</i></summary><blockquote>

> ```
> '- optional, read from `.apparatecfg` if not provided'),
> ```
Please remove the trailing comma.
</blockquote></details>

OK.
___
*[apparate/cli_commands.py, line 168 at r2](https://reviewable.io/reviews/aquicore/apparate/1#-LkQWY0NCkXPgohmfwH0:-LkUgYKP5_A12PwBk98x:b2nhktp) ([raw file](https://github.com/aquicore/apparate/blob/d7d27dd1426cf7e491d7ce385189fc11ff2d9d6f/apparate/cli_commands.py#L168)):*
<details><summary><i>Previously, nate-aq (Nathan Bittinger) wrote…</i></summary><blockquote>

> ```
> show_default=True,
> ```
Please remove the trailing comma.
</blockquote></details>

OK.
___
*[apparate/cli_commands.py, line 195 at r2](https://reviewable.io/reviews/aquicore/apparate/1#-LkQWVQk1ksRdtJ8YOqX:-LkUgYurDLIVDTpcFCwt:b2nhktp) ([raw file](https://github.com/aquicore/apparate/blob/d7d27dd1426cf7e491d7ce385189fc11ff2d9d6f/apparate/cli_commands.py#L195)):*
<details><summary><i>Previously, nate-aq (Nathan Bittinger) wrote…</i></summary><blockquote>

> ```
> update_clusters=True,
> ```
Please remove the trailing comma.
</blockquote></details>

OK.

**Comment by nate-aq** [comment]
___
*[apparate/cli_commands.py, line 147 at r2](https://reviewable.io/reviews/aquicore/apparate/1#-LkQWKEU4lbbpTTOoCEf:-LkUgclzEI7sMtjJS0yL:b2nhktp) ([raw file](https://github.com/aquicore/apparate/blob/d7d27dd1426cf7e491d7ce385189fc11ff2d9d6f/apparate/cli_commands.py#L147)):*
<details><summary><i>Previously, nate-aq (Nathan Bittinger) wrote…</i></summary><blockquote>

> OK.
OK.
</blockquote></details>

OK.

**Review by nate-aq — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/aquicore/apparate/1#-:-LkUgksi-YPJkemqyJGc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by msakauye — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/aquicore/apparate/1#-:-LkUh9n53r9WtQpS1A71:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mgsosna — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/aquicore/apparate/1#-:-LkUlmla2B4F8mHnhxA0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by nate-aq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aquicore/apparate/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
